name: Build packer vm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-source:
    runs-on: ubuntu-latest
    name: Build optee source code
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup optee
        run: |
          curl -L https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          sudo mv ~/repo /bin/repo
          sudo chmod a+x /bin/repo
          git config --global user.name 'SCOPELAB'
          git config --global user.email 'whoami@scope.lab'

      - name: Clone optee source code and build
        run: |
          mkdir -p ~/optee
          cd ~/optee
          repo init -u https://github.com/NTHU-SCOPELAB/manifest.git -m qemu_v8.xml
          repo sync
          rm -rf optee_examples/aes
          cd build
          make -j4 toolchains
          make -j4

      - name: Upload built optee binary
        uses: actions/upload-artifact@v4
        with:
          name: optee_binary
          path: ~/optee


  packer:
    runs-on: ubuntu-latest
    needs: build-source
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download built optee binary
        uses: actions/download-artifact@v4
        with:
          name: optee_binary
          path: ./build-image/cloud-init

      - name: Check the downloaded artifact
        run: |
          ls -la ./build-image/cloud-init

      - name: Install VirtualBox and Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y virtualbox virtualbox-guest-additions-iso

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        working-directory: ./build-image
        id: init
        run: packer init .

      - name: Run `packer validate`
        working-directory: ./build-image
        id: validate
        run: packer validate .

      - name: Build packer image
        working-directory: ./build-image
        run: |
          packer build -only=virtualbox-iso.practice-vm .

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Split the vm file in to chunks of 2G before uploading
        working-directory: ./build-image/build
        run: |
          zip -s 1g -r -0 practice-vm.zip practice-vm.ova

      - name: Create a new release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          make_latest: true
          generate_release_notes: true
          fail_on_unmatched_files: false
          prerelease: false
          files: |
            build-image/build/practice-vm.z*
