name: Build packer vm

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'cloud-init/**' 
      - '*.pkr.hcl'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'cloud-init/**'
      - '*.pkr.hcl'

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install VirtualBox and Dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y virtualbox virtualbox-guest-additions-iso

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        id: init
        run: packer init .

      - name: Run `packer validate`
        id: validate
        run: packer validate .

      - name: Build packer image
        run: |
          packer build -only=virtualbox-iso.practice-vm .

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          make_latest: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          prerelease: false
          files: |
            build/practice-vm.ova
